#!/bin/sh

DPI=96

xrandr --dpi "$DPI"
#This file runs when a DM logs you into a graphical session.
#If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			# set the background with the `setbg` script
# xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info

xset r rate 300 50 &	# Speed xrate up

autostart="mpd xcompmgr redshift dunst unclutter lxpolkit pwsinks"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

#ensure that xrdb has finished running before moving on to start WM/DE
[-n "$xrdbpid" ] && wait "$xrdbpid"
