theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "┆"

[editor.soft-wrap]
enable = true
max-wrap = 25
